### ISSUE TITLE
NoteView Boxes aren't locked to canvas

### ISSUE THREAD

**Issue by 7imbrook** [RITAccess/accessmath#102]
Notes on the screen move around separate of panning and glitch around the screen.

**Comment by rasampratik** [comment]
I am working on that, somehow the the view containing notes is not initializing properly to the mainView which is returned by contentView().

**Comment by 7imbrook** [comment]
`TextNoteView` and `TextNoteViewController` on `feature/notetaking` fix this issue with height and width stretching set to 0.
