### ISSUE TITLE
Favorites tableview does not need gestures on it

### ISSUE THREAD

**Issue by 7imbrook** [RITAccess/accessmath#104]
Swipe to delete is a feature that is a part of tableview, and so is tap to add. I'll be removing those gestures and they will have to be reimplemented using the tableview features.

**Comment by piperchester** [comment]
I originally implemented the table view gestures, but they were less intuitive than just tapping the screen. Because the table is so small, it's much harder to swipe to add and/or delete items.

**Comment by 7imbrook** [comment]
They also just break the build so I removed them.

**Comment by piperchester** [comment]
Lies and slander :-1:

**Comment by piperchester** [comment]
But okay.
