### ISSUE TITLE
Layout issues

### ISSUE THREAD

**Issue by 7imbrook** [RITAccess/accessmath#119]
![Imgur](http://i.imgur.com/VOS5lj3.png)
This is just a living nightmare

**Comment by 7imbrook** [comment]
But checkout [this](https://gist.github.com/7imbrook/8306619#comment-1180121)

**Comment by piperchester** [comment]
Wat.

**Comment by piperchester** [comment]
If this blackmagics like I hope it will we have some praise for the Objective-C gods.
