### ISSUE TITLE
Segue to the about page does not work

### ISSUE THREAD

**Issue by chtinahow** [RITAccess/accessmath#177]

**Comment by 7imbrook** [comment]
Thats a quick fix in storyboard, it's just something we never added back. Just add the segue from the button to the about view. Then bind the back button to goBack in responders.

**Comment by MukeytheMuse** [comment]
Just adding the segue doesn't seem to help. I was actually wondering if this function: 
- (void)openAbout:(id)sender
  {
  [self performSegueWithIdentifier:@"toAbout" sender:self];
  }

should have something along those lines in it. Like how the notes button has @"open". (This is in RootMenuController.m).
