### ISSUE TITLE
Bad access of dismissal and and re-presenting of Shuffle mode 

### ISSUE THREAD

**Issue by piperchester** [RITAccess/accessmath#185]
Check out:

https://github.com/RITAccess/accessmath/blob/feature/184-note-shuffle-integration/AccessLecture/MoreShuffle.m#L485-L504

**Comment by MukeytheMuse** [comment]
Update: The saved texture disappears when two (or more) lectures are introduced; currently working on resolving this issue.

**Comment by piperchester** [comment]
Issue was fixed in d19254a
