### ISSUE TITLE
Dynamically Place Buttons

### ISSUE THREAD

**Issue by piperchester** [RITAccess/accessmath#31]
Currently buttons are hardcoded. They need to seek the display's bounds to adjust their position appropriately.

**Comment by 7imbrook** [comment]
You can add contraints in code, but I defiantly sugest using interface builder for this.

**Comment by piperchester** [comment]
The issue description is poorly worded. I'm using IB but I need to add constraints in code.

**Comment by piperchester** [comment]
Added constraints within `LectureViewController`.
