### ISSUE TITLE
Grouping Buttons

### ISSUE THREAD

**Issue by rasampratik** [RITAccess/accessmath#41]
Buttons can be grouped together in a container so that they configured all at once.

**Comment by piperchester** [comment]
My best suggestion for this issue is to create a view, and then add the buttons to that view, but I'm honestly not sure. 

I definitely agree that we need a better a system to manage button location.

**Comment by 7imbrook** [comment]
Ive mentioned constraints before, and I know they never work like they should. But sometimes the best bet is to start from scratch, make a new VC in storyboard and re make the layout. Code can stay the same.

**Comment by piperchester** [comment]
Sigh, looks like that might be the case on this one. I'll investigate once I resolve our popover issue.

**Comment by piperchester** [comment]
Currently being handled in re-architecture of app. Remember those constraints!
