### ISSUE TITLE
Implement Primitives

### ISSUE THREAD

**Issue by piperchester** [RITAccess/accessmath#58]
We agreed it might be useful to be able to drag a few small shapes onto the screen.

Some shape ideas include:
- Arrows
- Circles
- Boxes
- Stars

**Comment by rasampratik** [comment]
These shapes are to be implemented on the notes too?

**Comment by piperchester** [comment]
I don't think so @rasampratik . They're mainly going to be used for the draw controller.

**Comment by piperchester** [comment]
Currently stamping star images. Need to implement a selection mode somehow.

**Comment by piperchester** [comment]
Implemented cycle function through array of images.
