### ISSUE TITLE
Tap Zoom Broken on Multiple Views

### ISSUE THREAD

**Issue by piperchester** [RITAccess/accessmath#65]
~~Tap zoom returns the view to its original state, but doesn't function properly when using multiple views.~~
UPDATE: 
Implementing the following:
- [x] Pinch to zoom
- [x] Two finger tap to zoom in by an amount
- [x] Two finger pan
- [x] Full zoom out
- [x] "Standard" zoom in
- [x] "Standard" pan location
- [x] Zoom in/out limits
- [x] Pan limits

**Comment by piperchester** [comment]
Currently the view continues to scale 1.5 times and doesn't reset to `CGAffineTransfromIdentity`.

**Comment by piperchester** [comment]
This might interfere with notes, what do you think @rasampratik?

**Comment by 7imbrook** [comment]
Pan and zoom functionality from the subview standpoint is complete, see [LectureViewChild](https://github.com/RITAccess/accessmath/blob/Integration/AccessLecture/LectureViewContainer.h#L19-L57) protocol. Things to keep in mind with implementing:
- Bounds don't change, they will aways be the full canvas size
- Frame gets resized with transforms, transforms can be accessed off the view but shouldn't be modified

I will be finishing up the additional functionally of zooming and panning but the protocol should remain the same, `contentView` being the most important.
