### ISSUE TITLE
Memory usage on DrawView is unacceptable.

### ISSUE THREAD

**Issue by 7imbrook** [RITAccess/accessmath#76]
When moving to a larger canvas the drawView is using upwards of 90MB of ram, on newer devices this usage doesn't show, but performance is crap on older devices. Plus the usage may cause the app to not be approved by Apple. We need to look into more efficient drawing methods and defiantly use caching. 

Edit:
The new devices do have 1GB of ram, but most only have 512MB. Still using all of this is ridiculous. 

Edit 2:
Be sure to test higher resolutions (like 4K from #84) as well.

**Comment by piperchester** [comment]
Ouch, yeah that's absurd. Good thoughts with caching.

**Comment by piperchester** [comment]
Did you have success with the caching?

**Comment by 7imbrook** [comment]
Optimizing is still a work in progress, but not a top priority for the upcoming milestone. See #88

**Comment by piperchester** [comment]
:+1:

**Comment by 7imbrook** [comment]
[sprang/Brushes](https://github.com/sprang/Brushes) would be a great solution so we're not doing it on our own.

**Comment by piperchester** [comment]
Can finally close this issue! :beers:
