### ISSUE TITLE
Investigate connection bug on iOS 6

### ISSUE THREAD

**Issue by 7imbrook** [RITAccess/accessmath#79]
The stream fails to finish download on the iPad running iOS 6, doesn't always happen.

**Comment by 7imbrook** [comment]
Could have something to do with the hard coded test we have.

**Comment by piperchester** [comment]
Does this have anything to do with #98 ?

**Comment by 7imbrook** [comment]
obsoletely nothing, the issue is a completely different situation, but it's minor at the moment.
