### ISSUE TITLE
DrawViewController locks up at higher resolutions

### ISSUE THREAD

**Issue by 7imbrook** [RITAccess/accessmath#84]
When running a a full 4K (4096 × 3112) canvas size, you are able to draw a few lines before it just stops working all together.

**Comment by piperchester** [comment]
Any suggestions to resolve this?

**Comment by 7imbrook** [comment]
We don't run at 4K... behavior works at 1080p. Optimizations will need to happen before higher res can be supported.

**Comment by piperchester** [comment]
Right - I don't think this is an issue because we're not running at 4K.

**Comment by 7imbrook** [comment]
However it is a good test when we start working on #76

**Comment by piperchester** [comment]
Let's make a note of this in #76 but close the issue.

Edit:
Noted the test in #76.
