### ISSUE TITLE
Lecture attributes

### ISSUE THREAD

**Issue by rasampratik** [RITAccess/accessmath#87]
Is there a way to fetch lecture attributes like name, most recent updated timestamp from the stream??

**Comment by 7imbrook** [comment]
I'll get on  this. Streams don't have timestamps yet. But I'll update ALNetworkInterface to provide some for meta data

**Comment by 7imbrook** [comment]
Because timestamps aren't 100% yet, could be time since 1970 or time since beginning of stream. I don't have a good way of providing that information yet. But you can get the current lecture name from the server with `getCurrentLectureName`

``` objective-c
AccessLectureAppDelegate *app = [UIApplication sharedApplication].delegate;
[app.server getCurrentLectureName];
```
