### ISSUE TITLE
Coding Guidelines Discussion 

### ISSUE THREAD

**Issue by 7imbrook** [RITAccess/accessmath#89]
### Discussion thread for coding guidelines

See the wiki about our coding guidelines [here](https://github.com/RITAccess/accessmath/wiki/Coding-Guidelines)

**Comment by piperchester** [comment]
What about class extensions? Are we following egyptian style bracing?

**Comment by 7imbrook** [comment]
Class extensions should not be using bracing

``` objective-c
@interface ClassName ()

@end
```

**Comment by piperchester** [comment]
Nice :ok_hand:. What about class declarations. Egyptian or:

``` objective-c
@implementation ConnectionViewController
{
    ALNetworkInterface *server;
    QRScanner *scanner;
    AVCaptureVideoPreviewLayer *preview;
    UIButton *cancelButton;
    BOOL isScanning;
}
```

**Comment by 7imbrook** [comment]
I like Egyptian, why don't you go ahead and add that to the coding guidelines @piperchester

**Comment by piperchester** [comment]
:+1: - on it.

**Comment by piperchester** [comment]
Closing this issue for now as it seems we've had 2 weeks since any discussion on our coding guidelines. We can re-open if we need to discuss :+1:
