### ISSUE TITLE
Update Menu Icons

### ISSUE THREAD

**Issue by 7imbrook** [RITAccess/accessmath#92]
Stream view is the main concern, I just kinda picked a rando icon for that
- [x] Save Button
- [x] Notes Button
- [x] DrawView
- [x] Stream
- [x] Zoom Button
- [x] Cancel
- [x] Recycle
- [x] Resize
- [x] Pin

Any others?

**Comment by piperchester** [comment]
They're probably some notes buttons that we need to, right @rasampratik ?

**Comment by rasampratik** [comment]
yes, i have added a few from google, let me know if they are ok.i am currently working on the notes resizing, since they are not resizing properly after zooming in or panning

**Comment by piperchester** [comment]
I think we're going to create all of our own custom icons. I'll add the .ais to a AccessMathResources directory for anyone to modify the icons to his liking :+1:

**Comment by piperchester** [comment]
@rasampratik Is there anyway you can implement the ColorSegmentedControl that I'm using instead of having colored .pngs?
