### ISSUE TITLE
Integrate ColorSegmentedControl into NotesViewController

### ISSUE THREAD

**Issue by piperchester** [RITAccess/accessmath#96]
We'll reduce the number of .pngs we need to include, as well as just clearing up some code. 

Also, we're adhering to a pragmatic tip: DRY. :+1:

**Comment by rasampratik** [comment]
working on it.

**Comment by 7imbrook** [comment]
If this is ready to bring into Integration @rasampratik it's the last issue before we do our last checks before merge.
