### ISSUE TITLE
iOS 6 behavior

### ISSUE THREAD

**Issue by 7imbrook** [RITAccess/accessmath#97]
QR scanning functionality should just not be exposed on iOS 6. AKA no "Current iOS Does Not Support QR Scanning"

**Comment by piperchester** [comment]
Don't you think we should notify the user of not being able to use QR support if we detail it as a feature?

**Comment by piperchester** [comment]
Alright :ok_hand: let's be sure to document support in some menu, settings, about, etc.

**Comment by 7imbrook** [comment]
Features that are version specific are shown in app description page in the app store, features do not need to be documented in the application. It adds more clutter to the application then needs to be there.

**Comment by piperchester** [comment]
Even better, :+1: I've got a bit of time right now, I'll remove the banner.
