### ISSUE TITLE
Lecture Connections Broken

### ISSUE THREAD

**Issue by 7imbrook** [RITAccess/accessmath#98]
@piperchester during your work on connectionViewController, the connection functionality stopped working.

**Comment by piperchester** [comment]
Yikes. Can you diff blame me the code that removed the connection?

**Comment by 7imbrook** [comment]
It was a few things, I toke care of the issue. Because you used a segue, you completely skipped over where the delegate was set so connection view controller had no one to call back to. It needed to be instantiated and presented differently now we weren't using xibs.
