### ISSUE TITLE
Testing Guidlines

### ISSUE THREAD

**Issue by 7imbrook** [RITAccess/accessmath#99]
We should have tests to start, but a lot of what we have we can't test easily. But some things to keep in mind while working are:
- Relationships and connections between classes shouldn't break
- Instantiation of classes being done consistently to prevent unwanted behavior
- Avoiding renaming methods, if needed use xcode's redaction tools
- Flow of information between classes.
###### This issue is discussing general workflow of the application

Edit:
- We're still using the SenTesting so we can continue to support iOS 6. 

Edit 2:
- Try to name your test classes `ClassTest.m` if you can so we can maintain consistency.

**Comment by piperchester** [comment]
Great idea with the guidelines. I'd like to move these to a Wiki page though. What do you think, @7imbrook?

**Comment by 7imbrook** [comment]
I want to leave a discussion open if we do, because wikis are awkward to do that on,

**Comment by piperchester** [comment]
I like that - let's leave this open for a while to iron out any issues or thoughts we have, then move to a wiki page.

**Comment by 7imbrook** [comment]
:+1:

**Comment by piperchester** [comment]
Just a thought, we're still using SenTest and not XCTest right? Or do you think we're able to use XCTest.

**Comment by 7imbrook** [comment]
Just stick with OCTest (SenTest)

**Comment by piperchester** [comment]
Another thought - are we naming our tests `DrawViewTests.m` or just `DrawView.m`? I'm in favor of the more descriptive naming, although after a quick search I couldn't find much of a consensus. 

Thoughts, @7imbrook ? (Note: tagging you so you'll see the question faster :+1: )

**Comment by 7imbrook** [comment]
So I personally avoid putting the test at the end, the convention for all the test cases is test_____ because thats how both OCUnit and XCTest look for tests. The class name doesn't matter, I leave out the test because it's in so many other places. Plus it has a separate target altogether so there can't be a naming conflict.

**Comment by piperchester** [comment]
Right right. But if I wanted to name a test `DrawView.m`, I wouldn't be able to because it's a duplicate class. I'd get the error: `Duplicate interface definition`. 

So can we name our test classes `ClassTest.m`?

**Comment by 7imbrook** [comment]
If you must, I feel like having it under that target is plenty for it being classified as a test.

**Comment by piperchester** [comment]
:+1: it totally is - just indulging my incessant need for explicitness now :neckbeard:

**Comment by 7imbrook** [comment]
On the note of testing, here's my pre-push hook for git.
[https://gist.github.com/7imbrook/4ae8916e7ed34a329e6c](https://gist.github.com/7imbrook/4ae8916e7ed34a329e6c)
